src/AAE/AMBundle/Entity/Slider.php
<?php

namespace AAE\AMBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Slider
 *
 * @ORM\Table(name="slider")
 * @ORM\Entity(repositoryClass="AAE\AMBundle\Repository\SliderRepository")
 * @Vich\Uploadable
 */
class Slider
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    private $image;
    
    
    /**
     * @ORM\ManyToOne(targetEntity="AAE\AMBundle\Entity\Ecran")
     * @ORM\JoinColumn(nullable=true)
     */
    private $ecran;

    /**
     * @Vich\UploadableField(mapping="slider_home", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime
     */
    private $updatedAt;
    
     /**
     * @var string
     *
     * @ORM\Column(name="ordre", type="string", length=5, unique=false)
     */
    private $ordre;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string
     */
    private $titre;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string
     */
    private $url;


    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function setImage($image)
    {
        $this->image = $image;
    }

    public function getImage()
    {
        return $this->image;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     *
     * @return Slider
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set ordre
     *
     * @param string $ordre
     *
     * @return Slider
     */
    public function setOrdre($ordre)
    {
        $this->ordre = $ordre;

        return $this;
    }

    /**
     * Get ordre
     *
     * @return string
     */
    public function getOrdre()
    {
        return $this->ordre;
    }

    /**
     * Set ecran
     *
     * @param string $ecran
     *
     * @return Slider
     */
    public function setEcran($ecran)
    {
        $this->ecran = $ecran;

        return $this;
    }

    /**
     * Get ecran
     *
     * @return string
     */
    public function getEcran()
    {
        return $this->ecran;
    }

    /**
     * Set titre
     *
     * @param string $titre
     *
     * @return Slider
     */
    public function setTitre($titre)
    {
        $this->titre = $titre;

        return $this;
    }

    /**
     * Get titre
     *
     * @return string
     */
    public function getTitre()
    {
        return $this->titre;
    }

    /**
     * Set url
     *
     * @param string $url
     *
     * @return Slider
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }
    
    public function getLegende(){
        if($this->getUrl()!=null){
            return $this->getTitre().' - <a target="_blank" href="'.$this->getUrl().'">'.$this->getUrl().'</a>';
        } else {
            return $this->getTitre();
        }
    }
    
}

src/AAE/AMBundle/Controller/MobilierController.php
<?php

namespace AAE\AMBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use AAE\AMBundle\Entity\Categorie;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;

class MobilierController extends Controller
{

    public function indexAction(Categorie $categorie,Request $request){
        //Récupération des produits visible par catégorie
        $queryProduits = $this->getDoctrine()->getManager()->getRepository('AAEAMBundle:Produit')->findByCategory($categorie);
        
        $paginator  = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
            $queryProduits, 
            $request->query->getInt('page', 1),
            18
        );
        
        return $this->render('AAEAMBundle:Mobilier:index.html.twig',array(
            'pagination' => $pagination,
            'categorie' => $categorie,
        ));
    }
    
    public function viewAction($ref){
        $em = $this->getDoctrine()->getManager();
        
        $produit = $em->getRepository('AAEAMBundle:Produit')->findOneByReference($ref);
        
        return $this->render('AAEAMBundle:Mobilier:view.html.twig',array(
            'produit' => $produit,
        ));
    }
    
    public function realisationAction()
    {
        //Récupération de la liste des catégories
        $repo = $this->getDoctrine()->getManager()->getRepository('AAEAMBundle:Slider');
        
        $imgMobilier = $repo->findByNomEcran('mobilier')->getResult();
        
        
        return $this->render('AAEAMBundle:Mobilier:realisation.html.twig',array(
            'imgs' => $imgMobilier,
        ));
    }
    
    public function surMesureAction()
    {
        return $this->render('AAEAMBundle:Mobilier:surMesure.html.twig');
    }
    
    
    public function rechercheAction(Request $request)
    {
        // Requête AJAX
        if($request->isXmlHttpRequest()){
            $recherche = $request->get('recherche');
            
            $data = $this->getDoctrine()->getManager()->getRepository('AAEAMBundle:Produit')->findByLike($recherche);
            
            return new JsonResponse($data);            
        }
        
        
        
        return $this->render('AAEAMBundle:Mobilier:recherche.html.twig');
    }
    
    
    
    
    public function listeCategoryAction($idCategory = null){
        //Récupération de la liste des catégories
        $categories = $this->getDoctrine()->getManager()->getRepository('AAEAMBundle:Categorie')->findBy(array(),array(
            'ordre' => 'ASC',
        ));
        
        return $this->render('AAEAMBundle:Mobilier:listeCategory.html.twig',array(
            'categories' => $categories,
            'idCategory' => $idCategory,
        ));
    }
    
    public function subMenuAction($active,$title){
        //Récupération de la liste des catégories
        $categories = $this->getDoctrine()->getManager()->getRepository('AAEAMBundle:Categorie')->findBy(array(),array(
            'ordre' => 'ASC',
        ));
        
        return $this->render('AAEAMBundle:Mobilier:subMenu.html.twig',array(
            'categories' => $categories,
            'active' => $active,
            'title' => $title,
        ));
    }
    
    
    
    
    
    
}

src/AAE/AMBundle/Resources/views/Mobilier/index.html.twig
{% extends "AAEAMBundle::layout.html.twig" %}

{% block title %}Mobilier - Catalogue{% endblock %}
{% set title = 'Mobilier - Catalogue - '~ categorie.nom %}
{% block body %} 
    <div id="catalogue" class="container-fluid">
        <div class="row">
            <div id="container-title">
                <div class="container">
                    <div class="row">
                        <h1>{{ title }}</h1>
                    </div>
                </div>
            </div>
                    
            <div class="hidden-lg hidden-md" id="img-header" style="background-image: url('{{ asset('bundles/aaeam/images/catalogue/header/menu.jpg') }}')" /></div>

       
            <div id="container-header" class="container">
                <div id="content" class="row">
                    
                    <div class="col-lg-12">
                        <div class="row">
                            {{ render(controller('AAEAMBundle:Mobilier:subMenu',{ 'active': 1,'title' : title })) }}
                        </div>
                        <div class="row-fluid">
                            {{ render(controller('AAEAMBundle:Mobilier:listeCategory',{ 'idCategory': categorie.id })) }}
                        </div> 
                    </div>
                    
                    <div class="row">
                        <div id="liste-produit" class="col-lg-12">
                            {% for produit in pagination %} 
                                <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6 item-produit">
                                    <div class="col-lg-12">
                                        <a href="{{ path('aaeam_activites_mobilier_catalogue_produit',{'ref':produit.reference}) }}">
                                            <img src="{{ asset( path.img.produits ~ produit.image) }}" />
                                        </a>
                                    </div>
                                    <div class="ref col-lg-12">
                                        {{ produit.reference }}
                                        <span v-if="exist('{{ produit.reference }}')" v-on:click="addProduct('{{ produit.reference }}','{{ asset( path.img.produits ~ produit.image) }}')" class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
                                        <span v-else v-on:click="removeProduct('{{ produit.reference }}')" class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div id="navigation" class="row">
                    <div class="col-xs-12">
                        {{ knp_pagination_render(pagination) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block stylesheets %}
    
    {{ parent() }}

    {% stylesheets filter='scssphp'
        '@AAEAMBundle/Resources/public/scss/Components/subMenu.scss'
        '@AAEAMBundle/Resources/public/scss/Components/imgHeader.scss'
        '@AAEAMBundle/Resources/public/scss/Components/header.scss'
        '@AAEAMBundle/Resources/public/scss/Mobilier/listeCategory.scss'
        '@AAEAMBundle/Resources/public/scss/Mobilier/index.scss' 
    %}
        <link rel="stylesheet" href="{{ asset_url }}" type="text/css" />
    {% endstylesheets %}

{% endblock %}

src/AAE/AMBundle/Resources/views/Mobilier/listeCategory.html.twig
<ul id="list-category" class="hidden-xs hidden-sm">
    {% for categorie in categories %}
    <li>
        <a href="{{ path('aaeam_activites_mobilier_catalogue_categorie',{'id':categorie.id}) }}" class="item-catalogue {% if idCategory is not null and categorie.id == idCategory %}active{% endif %}  {% if not loop|last %}border{% endif %}" 
           {% if idCategory is not null and categorie.id == idCategory %}
                style="background-image: url('{{ asset( path.img.categorie_active ~ categorie.iconeActive) }}');"
           {% else %}
                style="background-image: url('{{ asset( path.img.categorie ~ categorie.icone) }}');"
           {% endif %}
           >
            <span>{{ categorie.nom }}</span>
        </a>
    </li>
    {% endfor %}
</ul>

src/AAE/AMBundle/Resources/views/Mobilier/realisation.html.twig
{% extends "AAEAMBundle::layout.html.twig" %}

{% block title %}Mobilier - Nos réalisations{% endblock %}
{% set title = 'Mobilier - Nos réalisations' %}
{% block body %}
    <div id="realisation" class="container-fluid">
        <div class="row">
            <div id="container-title">
                <div class="container">
                    <div class="row">
                        <h1>{{ title }}</h1>
                    </div>
                </div>
            </div>
            
            <div id="img-header" style="background-image: url('{{ asset('bundles/aaeam/images/catalogue/header/menu.jpg') }}')" /></div>
        
        
            <div id="content" class="container">
                <div class="row">
                    {{ render(controller('AAEAMBundle:Mobilier:subMenu',{ 'active': 3, 'title' : title })) }}
                </div>  
                    
                    
                <div id="gallerie" class="row">
                    {% for img in imgs %} 
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 img-realisation">
                            <img data-index="{{ loop.index0 }}" data-titre="{{ img.legende }}" src="{{ asset( path.img.slider ~ img.image) }}" />
                            <div class="realisation-titre">{{ img.titre }}</div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
                        
                        
                        
                        
    <!-- Root element of PhotoSwipe. Must have class pswp. -->
    <div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

        <!-- Background of PhotoSwipe. 
             It's a separate element, as animating opacity is faster than rgba(). -->
        <div class="pswp__bg"></div>

        <!-- Slides wrapper with overflow:hidden. -->
        <div class="pswp__scroll-wrap">

            <!-- Container that holds slides. PhotoSwipe keeps only 3 slides in DOM to save memory. -->
            <div class="pswp__container">
                <!-- don't modify these 3 pswp__item elements, data is added later on -->
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
                <div class="pswp__item"></div>
            </div>

            <!-- Default (PhotoSwipeUI_Default) interface on top of sliding area. Can be changed. -->
            <div class="pswp__ui pswp__ui--hidden">

                <div class="pswp__top-bar">

                    <!--  Controls are self-explanatory. Order can be changed. -->

                    <div class="pswp__counter"></div>

                    <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>

                    <button class="pswp__button pswp__button--share" title="Share"></button>

                    <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>

                    <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>

                    <!-- Preloader demo http://codepen.io/dimsemenov/pen/yyBWoR -->
                    <!-- element will get class pswp__preloader--active when preloader is running -->
                    <div class="pswp__preloader">
                        <div class="pswp__preloader__icn">
                          <div class="pswp__preloader__cut">
                            <div class="pswp__preloader__donut"></div>
                          </div>
                        </div>
                    </div>
                </div>

                <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                    <div class="pswp__share-tooltip"></div> 
                </div>

                <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
                </button>

                <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
                </button>

                <div class="pswp__caption">
                    <div class="pswp__caption__center"></div>
                </div>
            </div>
        </div>
    </div>                    
                        
{% endblock %}

{% block stylesheets %}
    
    {{ parent() }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/default-skin/default-skin.min.css" />

    {% stylesheets filter='scssphp'
        '@AAEAMBundle/Resources/public/scss/Components/header.scss' 
        '@AAEAMBundle/Resources/public/scss/Components/imgHeader.scss' 
        '@AAEAMBundle/Resources/public/scss/Components/subMenu.scss' 
        '@AAEAMBundle/Resources/public/scss/Mobilier/realisations.scss' 
    %}
        <link rel="stylesheet" href="{{ asset_url }}" type="text/css" />
    {% endstylesheets %}

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.js"></script>    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe-ui-default.min.js"></script>
    
    <script>
        
        var openPhotoSwipe = function(items,index) {
            var pswpElement = document.querySelectorAll('.pswp')[0];

            {#// build items array
            var items = [
                {
                    src: 'https://farm2.staticflickr.com/1043/5186867718_06b2e9e551_b.jpg',
                    w: 964,
                    h: 1024
                },
                {
                    src: 'https://farm7.staticflickr.com/6175/6176698785_7dee72237e_b.jpg',
                    w: 1024,
                    h: 683
                }
            ];#}

            // define options (if needed)
            var options = {
                index : index,
                getThumbBoundsFn: function(index) {

                    // find thumbnail element
                    var thumbnail = document.querySelectorAll('.img-realisation img')[index];

                    // get window scroll Y
                    var pageYScroll = window.pageYOffset || document.documentElement.scrollTop; 
                    // optionally get horizontal scroll

                    // get position of element relative to viewport
                    var rect = thumbnail.getBoundingClientRect(); 

                    // w = width
                    return {x:rect.left, y:rect.top + pageYScroll, w:rect.width};

                },                
            };

            var gallery = new PhotoSwipe( pswpElement, PhotoSwipeUI_Default, items, options);
            gallery.init();
        };

{#        openPhotoSwipe();#}


        $('.img-realisation img').click(function(){
            var index = $(this).data('index');
            var items = [];
            $('.img-realisation img').each(function() {
                var obj = {
                    src : $(this).attr('src'),
                    w : $(this)[0]['naturalWidth'],
                    h : $(this)[0]['naturalHeight'],
                    author : 'dsqdsqdq',
                    title : $(this).data('titre'),
                }
                items.push(obj);
            });
            
            openPhotoSwipe(items,index);
        });
{#        document.getElementById('btn').onclick = openPhotoSwipe;#}
        
    </script>
{% endblock %}

src/AAE/AMBundle/Resources/views/Mobilier/recherche.html.twig
{% extends "AAEAMBundle::layout.html.twig" %}

{% block title %}Mobilier - Recherche{% endblock %}
{% block body %}
    <div id="container-recherche">
        <div class="container-fluid">
            <div class="row-fluid">
                <div id="container-title">
                    <div class="container">
                        <div class="row">
                            <h1 v-if="recherche==''">Recherche</h1>
                            <h1 v-else >Recherche : ${ recherche }</h1>
                        </div>
                    </div>
                </div>      
            </div>
        </div>

        <div id="recherche" class="container-fluid">
            <div class="row-fluid">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="input-group">
                                <input v-model="recherche" type="text" class="form-control" placeholder="Rechercher" autofocus="true">
                                <span class="input-group-btn">
                                    <button class="btn btn-success" type="button"><span class="glyphicon glyphicon-search" aria-hidden="true"></span>  Rechercher</button>
                                </span>
                            </div>
                        </div>
                    </div>
                </div> 
            </div>
        </div>
        <div id="recherche-resultat" class="container-fluid">
            <div class="row-fluid">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            <h2 v-if="resultatRecherche.length==0">Aucun résultat ne correspond à votre recherche</h2>
                            <h2 v-else-if="resultatRecherche.length==1">Un produit correspond à votre recherche</h2>
                            <h2 v-else>${resultatRecherche.length} résultats de recherche</h2>
                        </div>
                        <div class="col-lg-12">
                            <div class="col-lg-2 col-md-3 col-sm-3 col-xs-6 item-produit" v-for="produit in resultatRecherche">
                                <div class="col-lg-12">
                                    <img v-on:click="linkToProduit(produit.reference)" v-bind:src="'{{ asset( path.img.produits ) }}'+produit.image" />
                                </div>
                                <div class="ref col-lg-12">
                                    ${ produit.reference }
                                    <span v-if="exist(produit.reference)" v-on:click="addProduct(produit.reference,'{{ asset( path.img.produits) }}'+ produit.image)"  class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
                                    <span v-else v-on:click="removeProduct(produit.reference)" class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div> 
            </div>
        </div>
    </div>
{% endblock %}

{% block stylesheets %}
    
    {{ parent() }}

    {% stylesheets filter='scssphp'
        '@AAEAMBundle/Resources/public/scss/Components/header.scss'
        '@AAEAMBundle/Resources/public/scss/Mobilier/recherche.scss' 
    %}
        <link rel="stylesheet" href="{{ asset_url }}" type="text/css" />
    {% endstylesheets %}

{% endblock %}

src/AAE/AMBundle/Resources/views/Mobilier/subMenu.html.twig
<div id="submenu">
    <ul class="hidden-xs hidden-sm">
        <li><a href="{{ path('aaeam_activites_mobilier_catalogue_categorie',{'id':1}) }}" type="button" class="btn btn-link {% if active == 1 %} active{% endif %}">Notre catalogue en ligne</a></li>
        <li><a href="{{ path('aaeam_activites_mobilier') }}" type="button" class="btn btn-link {% if active == 2 %} active{% endif %}">Notre offre sur-mesures</a></li>
        <li><a href="{{ path('aaeam_activites_mobilier_realisations') }}" type="button" class="btn btn-link {% if active == 3 %} active{% endif %}">Nos réalisations</a></li>
    </ul>
    <div class="dropdown hidden-lg hidden-md">
        <button id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="btn btn-link">
            {{ title }}
            <i class="material-icons">keyboard_arrow_down</i>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dLabel">
            <li><a href="{{ path('aaeam_activites_mobilier_catalogue_categorie',{'id':1}) }}" >Notre catalogue en ligne</a></li>
            <ul>
                {% for categorie in categories %}
                <li>
                    <a href="{{ path('aaeam_activites_mobilier_catalogue_categorie',{'id':categorie.id}) }}">{{ categorie.nom }}</a>
                </li>
                {% endfor %}
            </ul>
            <li><a href="{{ path('aaeam_activites_mobilier') }}" >Notre offre sur-mesures</a></li>
            <li><a href="{{ path('aaeam_activites_mobilier_realisations') }}" >Nos réalisations</a></li>
        </ul>
    </div>
</div>

src/AAE/AMBundle/Resources/views/Mobilier/surMesure.html.twig
{% extends "AAEAMBundle::layout.html.twig" %}

{% block title %}Mobilier - Notre offre sur-mesures{% endblock %}
{% set title = 'Mobilier - Sur-mesures' %}
{% block body %}
    <div id="catalogue" class="container-fluid">
        <div class="row">
            <div id="container-title">
                <div class="container">
                    <div class="row">
                        <h1>{{ title }}</h1>
                    </div>
                </div>
            </div>
            
            <div id="img-header" style="background-image: url('{{ asset('bundles/aaeam/images/catalogue/header/menu.jpg') }}')" /></div>
        
        
            <div id="content" class="container">
                <div class="row">
                    {{ render(controller('AAEAMBundle:Mobilier:subMenu',{ 'active': 2, 'title' : title })) }}
                </div>
                <div class="row-fluid">
                    <p>
                        Fort d’un savoir-faire artisanal de 30 ans, nous aimons à partager notre expérience dans la conception et la réalisation de tables, chaises, meubles, banquettes et poufs, pour le domaine de la restauration, des bars/ brasseries et de l'hôtellerie.
                        <br />
                        Que vous soyez professionnel CHR ou architecte d’intérieur, nous sommes aptes à réaliser le meuble "sur mesure" de votre choix, d'après vos plans et exigences.
                        <br />
                        Nous sommes créatifs et innovateurs, toujours à la recherche de nouveaux modèles afin de répondre aux tendances et à votre projet.
                    </p>
                    <a id="link_devis" href="{{ path('aaeam_contact') }}">
                        > demandez des renseignements, un devis ? 
                    </a>
                </div>   
            </div>
        </div>
    </div>
{% endblock %}

{% block stylesheets %}
    
    {{ parent() }}

    {% stylesheets filter='scssphp'
        '@AAEAMBundle/Resources/public/scss/Components/header.scss'
        '@AAEAMBundle/Resources/public/scss/Components/subMenu.scss'
        '@AAEAMBundle/Resources/public/scss/Components/imgHeader.scss'
        '@AAEAMBundle/Resources/public/scss/Mobilier/surMesure.scss' 
    %}
        <link rel="stylesheet" href="{{ asset_url }}" type="text/css" />
    {% endstylesheets %}

{% endblock %}